import type { NextPage } from "next";
import Head from "next/head";
import HomeScreen from "../components/Home";
import TitleHeader from "../components/TitleHeader";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <TitleHeader />
      <HomeScreen />
    </>
  );
};

export default Home;
